import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/header';
import {primary_font} from '@/functions/fonts';

export const metadata: Metadata = {
  title: 'Market Place',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={primary_font.variable}>
        <Header />
        <main>
        {children}
        </main>
      </body>
    </html>
  );
}
